### ISSUE TITLE
ARMv5 support

### ISSUE THREAD

**Issue by midzer** [alllexx88/Optware-ng#10]
It would be cool, if old ARMv5 architecture would be supported for Optware-ng

**Comment by alllexx88** [comment]
It is doable, and I've been poking around the idea of adding an armv5 feed, but I'm just not sure how much real demand there is for one. Adding a new feed always requires a lot of work and time, after all

**Comment by midzer** [comment]
As Optware IPKG packages arent updated anymore (like transmission), i am looking for an alternative.
Old NAS like Buffalo Linkstation are ARMv5 for example.

If you give me a hint where to start, i can help improve this fork.

**Comment by alllexx88** [comment]
This is probably not a place to request or give instructions, but sadly available Optware building how-to's are pretty outdated (at least, those I know of).
I believe, Buffalo Linkstation is ARMv5 EABI, and no FPU, correct? I've added an arm926ej-s uClibc-ng target. I'll commit the change after I build the toolchain. The next step would be building and fixing packages (I don't expect many 'new' issues, since the libc and kernel headers are the same versions as in ARMv7 target, so mostly we'll simply need to add new target 'buildroot-armv5eabi-ng' to the special cases: e.g., see [make/phoneme-advanced.mk](https://github.com/alllexx88/Optware-ng/blob/master/make/phoneme-advanced.mk): line 167).

If you're willing to help, then you can launch a full build of new feed with these commands (after I push the new target, of course). Starting from Optware-ng root:

```
make buildroot-armv5eabi-ng-target # this creates working dir we'll build feed in
cd  buildroot-armv5eabi-ng
make directories ipkg-utils # this creates needed directories and configures ipk packaging tools
make toolchain # this builds the toolchain
make # this tries to build the entire feed
```

And then fix issues you encounter and send Pull Requests with your fixes to me

**Comment by alllexx88** [comment]
@midzer ARMv5 feed is now online. Please test if you can

**Comment by midzer** [comment]
I just installed ARMv5 optware via given command. Everything went smoothly.
Installation of a package was successfull, too. Awesome :+1: 

Big ups for your work!
