### ISSUE TITLE
bash

### ISSUE THREAD

**Issue by steom** [alllexx88/Optware-ng#12]
/opt/lib/libc.so.1' library contains unsupported TLS
/bin/sh: can't load library 'libc.so.1'

after installing bash

platform armv7eabi asuswrt

**Comment by alllexx88** [comment]
It looks to me that your interactive shell got screwed because of `/opt/etc/profile` installed by `bash` package. I will repackage `bash` when I can (this will take a while due to some technical issues on my side), for now either edit `/opt/etc/profile` to comment out / delete this line:

    LD_LIBRARY_PATH=/opt/lib:${LD_LIBRARY_PATH}

Or just (re)move `/opt/etc/profile`

**Comment by steom** [comment]
yes,
you're right
i just deleting /opt/etc/profile
and everything is fine now

**Comment by alllexx88** [comment]
Great. Commit a21e88ceb0f9dd5082873abd14ffcd36c53ec77d should fix it, but due to technical failure I have to rebuild all feeds from scratch, so it'll take few days to update the binaries
